# Generated by Django 5.0.4 on 2024-04-25 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='creted_at',
            new_name='created_at',
        ),
    ]
